"""add missed_detections table

Revision ID: c48c7e7159e4
Revises: e5f6a7b8c9d0
Create Date: 2026-03-11 05:42:36.495732

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'c48c7e7159e4'
down_revision: Union[str, None] = 'e5f6a7b8c9d0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('admin_audit_log', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=True)
    op.drop_index(op.f('ix_admin_audit_log_id'), table_name='admin_audit_log')
    op.drop_index(op.f('ix_analyses_id'), table_name='analyses')
    op.drop_index(op.f('ix_detections_id'), table_name='detections')
    op.drop_index(op.f('ix_feedback_id'), table_name='feedback')
    op.drop_index(op.f('ix_tkpi_foods_id'), table_name='tkpi_foods')
    op.drop_index(op.f('ix_tkpi_foods_name_trgm'), table_name='tkpi_foods', postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_index(op.f('ix_tkpi_foods_tkpi_code_trgm'), table_name='tkpi_foods', postgresql_ops={'tkpi_code': 'gin_trgm_ops'}, postgresql_using='gin')
    op.drop_constraint(op.f('uq_tkpi_foods_tkpi_code'), 'tkpi_foods', type_='unique')
    op.drop_index(op.f('ix_tkpi_foods_tkpi_code'), table_name='tkpi_foods')
    op.create_index(op.f('ix_tkpi_foods_tkpi_code'), 'tkpi_foods', ['tkpi_code'], unique=True)
    op.drop_index(op.f('ix_yolo_tkpi_mapping_id'), table_name='yolo_tkpi_mapping')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_index(op.f('ix_yolo_tkpi_mapping_id'), 'yolo_tkpi_mapping', ['id'], unique=False)
    op.drop_index(op.f('ix_tkpi_foods_tkpi_code'), table_name='tkpi_foods')
    op.create_index(op.f('ix_tkpi_foods_tkpi_code'), 'tkpi_foods', ['tkpi_code'], unique=False)
    op.create_unique_constraint(op.f('uq_tkpi_foods_tkpi_code'), 'tkpi_foods', ['tkpi_code'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_tkpi_foods_tkpi_code_trgm'), 'tkpi_foods', ['tkpi_code'], unique=False, postgresql_ops={'tkpi_code': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_tkpi_foods_name_trgm'), 'tkpi_foods', ['name'], unique=False, postgresql_ops={'name': 'gin_trgm_ops'}, postgresql_using='gin')
    op.create_index(op.f('ix_tkpi_foods_id'), 'tkpi_foods', ['id'], unique=False)
    op.create_index(op.f('ix_feedback_id'), 'feedback', ['id'], unique=False)
    op.create_index(op.f('ix_detections_id'), 'detections', ['id'], unique=False)
    op.create_index(op.f('ix_analyses_id'), 'analyses', ['id'], unique=False)
    op.create_index(op.f('ix_admin_audit_log_id'), 'admin_audit_log', ['id'], unique=False)
    op.alter_column('admin_audit_log', 'meta',
               existing_type=postgresql.JSONB(astext_type=sa.Text()),
               nullable=False)
    # ### end Alembic commands ###
